### ISSUE TITLE
Enum input arguments not serializable

### ISSUE THREAD

**Issue by GeorgeEfstathiadis** [onnela-lab/forest#166]
We have an issue updating Forest in the development server. In the server, when running Forest tasks you provide inputs to the forest functions in json format. Thus all input arguments need to be serializable. In the latest version of Forest we have arguments such as `Frequency` Enum class in the `constants` module that can not be made into json input.

We need to replace the Enum classes with another type such as strings and ifelse statements in the code. @hackdna do you have any thoughts?

**Comment by hackdna** [comment]
AFAIK none of the Forest functions accept JSON as arguments. Could you provide more details like stack traces and links to the relevant code in Beiwe?

**Comment by GeorgeEfstathiadis** [comment]
I don't have any links to code to provide. My understanding is that when running a forest stack on the beiwe server you provide the arguments for the functions in json format, thus an Enum cannot be provided.

Maybe @biblicabeebli  can provide some more context.

**Comment by biblicabeebli** [comment]
(oops, this sat for a bit, my bad)

Yes, this is related to the forest task runner on Beiwe Backend.  We need to be able to serialize parameters so that they can be stored in the database.  It turns out that attribute access of python Enum [meta]classes returns some enum-related class type, not primitives or strings, and the python standard library json implementation blows up.

```
In [1]: import enum, json
In [2]: class whatsit(enum.Enum):
   ...:     whatever = "thing"
   ...:    
In [3]: json.dumps(whatsit.whatever)
------------------------***stacktrace***--------------------------------
TypeError: Object of type whatsit is not JSON serializable
```

There are various solutions, but the best one is to ensure that all "entrypoint" functions for Forest have json-serializeable types as defaults and as input types.  The reason this is preferable is because we want/need to be able to introspect on the default arguments of those entrypoint functions so that we don't need to update the backend whenever parameters change on those functions.  We store arguments so, provided the old parameters are still functional at all, we can re-run the tree on a participant that has uploaded new data.

My rec here is to [generally] just use a class for those defaults. The metaclass properties of the Enum type are not very valuable.

**Comment by biblicabeebli** [comment]
Ok, I've done some review. - forest dispatch is not my original work, there was supposed to already be parameter saving on the backend buuuut there isn't. I forgot about that. 🙄

So there isn't code I can point you to because it doesn't exist - yet. 

This is our tracking issue for the forest task dispatch page updates:
https://github.com/onnela-lab/beiwe-discussions/issues/109#issuecomment-1544293233  <- this comment is my most-up-to-date statement of work to be implemented related to this swath of the forest task dispatch code.

Here's a more specific statement of what the forest task dispatch needs:
- We need a mechanism of communicating parameter types for forest's tree entrypoints.
- If, for-example, dates/times need to be provided in string form I need to know that those parameters are actually dates/times because I need to provide the correct website ui element (date/time selector) for manual entry.
- We need well defined string conversions for those.
- We need the parameters to be exportable/serializeable.

Details on the feature driving serializeability:
- One of the features we want is an import/export function so that someone who is not intimately familiar with forest (me, @hydawo, a new onnela lab intern, an external sysadmin running their own beiwe instance) to be able to copy-paste a value in.  This is in addition to website form fields.

(Some of the footwork is simplified by adopting the `orjson` library.  It natively converts date and datetime objects to string form (pretty sure its the python isoformat), and it even looks like it actually handles those enum attributes correctly.  (The only weirdness is that its output is `bytes`, not `str`.)  It is also Extremely fast.

I would like to be able to introspect on the entrypoint functions themselves because that is hard to get wrong, but if there's another mechanism of presenting information to Beiwe I'm open to it.

**Comment by hackdna** [comment]
@biblicabeebli Thank you for the additional info. We can make Forest parameters serializable and/or add Forest function wrappers for Beiwe to call.

The question is whether this code belongs in Forest which would require Forest to know about Beiwe and follow changes to its code or should Beiwe serialize parameters itself since it knows exactly what it needs. Also, I think this serialization layer would be helpful to have in Beiwe in case there's ever a need to use another external library that we has no control over.

**Comment by biblicabeebli** [comment]
@hackdna Hassan wants this picked up, getting forest working on the servers again.  I don't think anything internal to Forest needs to change, just this addition.

Regarding your prior question Ilya, the code needs to be inside Forest because the concept is (eventually) for Beiwe to allow selecting a version (a commit) of Forest.  I need some code or data that I can consume to make the website provide appropriate parameters for that version of the forest tree. 

My proposal at this point is that we make a new file that contains some well defined classes and some instances of those classes.  I will assist whenever this needs updates but unless new UI needs come up it should be sufficient.

After putting this together I'm realizing this is not secure - the server is reaching to a github repository file for code to execute.  But also this is code that will install the target library so ... it doesn't matter? maybe?

I don't have time immediately to translate this into like a well specced data-only file that we parse. @GeorgeEfstathiadis  Can you do that? Take my untested-probably-broken-but-you-get-the-idea code below, and translate it into .... some decent YAML structure....?.  (Json does not allow comments, that seems kinda important, honestly it just needs to be an editable, human readable file that defines properties I can look at.
After that look at the needs of the existing trees, I need to know the current UI elements I will need for the website - do we need dates, datetimes, lists of strings, strings, booleans etc.  On the UI side (per-type) do we need dropdowns for strings, checkboxes (dropdowns?) for booleans, raw string entry, date picker, date-time picker etc.

Another topic is how and where should we validate that the spec matches the parameters for the target forest function that is run, and where/when do we run any such validation.

```
from typing import List

class BeiweForestConnector:
    target_function = None

# and then some classes of types of input options plus
class BeiweParameter:
    pass

class BeiweList(BeiweParameter):
    # beiwe website displays an error if any of these are not defined
    type = None 
    ui = None
    display_name = None
    default = None

# and then some subclasses that are like

class MyTree(BeiweForestConnector):
    target_function = "fully.import.path.to.my_tree's.function"  # needs to be a string
    
    # a list
    my_list_of_ints = BeiweList()
    my_list_of_ints.type = int
    my_list_of_ints.default = [31,13,8,255]
    my_list_of_ints.ui = "json_textfield"
    my_list_of_ints.display_name = "The List of Ints (see MyTree documentation)"
    
    # an int
    revolutions = BeiweInt()
    revolutions.range = range(1,10)
    revolutions.default = 3
    revolutions.ui = "slider"
    revolutions.display_name = "Revolutions"
    
    # a boolean
    run_in_reverse = BeiweBool()
    run_in_reverse.default = False
    run_in_reverse.ui = "dropdown"
    run_in_reverse.display_name = "Run Analysis in Reverse "
```

**Comment by GeorgeEfstathiadis** [comment]
@biblicabeebli I am not sure what you are trying to do with this code or what I should build with it. Where is this code supposed to be placed? Could you provide some more information on how this should be implemented?

**Comment by hackdna** [comment]
Thank you for the additional info @biblicabeebli. It looks like there are two separate issues: argument serialization for running Forest using Celery (current bug) and Forest version selection at runtime in Beiwe (potential future feature).

We should probably postpone dealing with the latter until the need and the requirements are more clear (see https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) and concentrate on the current issue in the meantime.

I think we can fairly easily solve this by inheriting from `int` or `str`. For example:
```python
from enum import IntEnum
class Frequency(IntEnum):
    """This class enumerates possible frequencies for summary data."""
    HOURLY = 1
    DAILY = 24
    HOURLY_AND_DAILY = 0
    THREE_HOURLY = 3
    SIX_HOURLY = 6
    TWELVE_HOURLY = 12
```
then we can do:
```python
>>> import json
>>> json.dumps(Frequency.HOURLY)
'1'
```
Should George and I create a branch with these changes for testing in Beiwe?

**Comment by biblicabeebli** [comment]
Woops I'm delnquent on updating my active issues this week, and you may have put in a bit of unnecessary work.

I just today got through the... crap that was in the way on the beiwe backend to run more recent versions of forest, as well as load the package on the frontend web servers. Current `develop` jasmine should work on the staging server, have not tested sycamore or ... the other one, but have not added oak.

As part of this work I scrapped the json parameter serializing. I know in principle there are security concerns using it unsafely, but we will just use pickle - we are literally planning to build a system that downloads a target version of a codebase and runs it, pickle isn't the problem.

I'm at the end of my week and a bit fried, I was planning to review this issue and the one about the json serializing and update both, but lost steam. I will get back to both issues monday(?) and get back to both of you on all fronts.

It also might be easiest if I make changes to forest since I am the consumer here, and then work with you two on review and make sure I haven't poked a hole somewhere.

**Comment by biblicabeebli** [comment]
(I am still actively working on code changes and cleanups in Beiwe Backend, not ready to sync yet.)

**Comment by biblicabeebli** [comment]
(last week had an emergency mobile bug that needed my attention, running through my github issue)

**Comment by biblicabeebli** [comment]
I am going to continue with the method I am using, e.g. pickle over json.

IntEnum definitely solves A serialization problem, but there are code accesses of the form `my_frequency_enum.value`, so code still fails to run. Its best if I make the effort to avoid code-level changes, and that's already accomplished with pickle.

As long as there is an understanding that changing certain function signatures require cross-codebase review before it can be merged into `develop` (or `main`) I think we are ok. I will put together a branch that adds a comment, and anything else I come across that might need to be changed, for discussion and review when the beiwe task running is working on more than just sycamore.

Those functions are currently:
```python
from forest.jasmine.traj2stats import gps_stats_main
from forest.oak.base import run as run_oak
from forest.sycamore.base import get_submits_for_tableau
from forest.willow.log_stats import log_stats_main
```

(The dynamic rendering of function signatures as parameters on the frontend is not an immediate requirement.)

**Comment by biblicabeebli** [comment]
On my branch, [beiwe-taskrunner](https://github.com/onnela-lab/forest/compare/develop...beiwe-taskrunner), I'm actually making use of the enums now because I need to separate out the daily files, so we are sticking with pickle.

**Comment by hackdna** [comment]
FYI, this seems to work with no errors:
```python
>>> from forest.constants import Frequency
>>> import json
>>> json.dumps(Frequency.DAILY.value)
'24'
```

**Comment by biblicabeebli** [comment]
Yes but that is because `.value` returns an integer. `Frequency.DAILY` returns... I think its a class called an EnumProperty? point is its not a json supported type, its a class.

**Comment by biblicabeebli** [comment]
I opened this issue, I believe this issue is resolved, so I'm going to close it.

**Comment by hackdna** [comment]
Just to clarify, my previous comment was in response to:
"ntEnum definitely solves A serialization problem, but there are code accesses of the form my_frequency_enum.value, so code still fails to run."
